twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      teleop_smoothed:
        topic: cmd_vel/teleop_smoothed
        timeout: 0.5
        priority: 10
      teleop:
        topic: cmd_vel/teleop
        timeout: 0.5
        priority: 10
      nav_cmd:
        topic: cmd_vel/nav
        timeout: 1.0
        priority: 5
