services:
  base:
    image: ${MTT_IMAGE:-mtt_tools:devel}
    working_dir: ${WORKSPACE}
    environment:
      - WORKSPACE
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION
      - USER=mtt
      - HOME=/home/mtt
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
    stop_signal: SIGINT
    volumes:
      - ${WORKSPACE}:${WORKSPACE}
      - ${HOME}/.ros:/home/mtt/.ros
      - ${HOME}/.bash_history:/home/mtt/.bash_history
      - ${HOME}/.config/ros.org:/home/mtt/.config/ros.org
      - ${HOME}/.gazebo:/home/mtt/.gazebo
      - ${HOME}/.gitconfig:/home/mtt/.gitconfig:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  ros_runtime_base:
    extends:
      service: base
    network_mode: host
    pid: host
    ipc: host
    cap_add:
      - NET_ADMIN

  x11_base:
    extends:
      service: ros_runtime_base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR:-/run/user/1000}:${XDG_RUNTIME_DIR:-/run/user/1000}
      - ${HOME}/.Xauthority:/home/mtt/.Xauthority:ro
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input
    environment:
      - XAUTHORITY=/home/mtt/.Xauthority
