#!/bin/bash
# setup_udev_reach_rs.sh
#
# Detects connected Emlid Reach RS receivers and installs udev rules:
#
#   Single-antenna mode (1 receiver):
#     /dev/reach_rover  → the rover (rear-center, single-antenna RTK setup)
#
#   Dual-antenna mode (2 receivers):
#     /dev/reach_left   → left  antenna (port side)
#     /dev/reach_right  → right antenna (starboard side)
#     /dev/reach_rover  → same physical device as reach_left (primary)
#
# Usage:
#   1. Connect Reach RS receiver(s) via USB
#   2. Run: sudo bash scripts/setup_udev_reach_rs.sh
#   3. Reload udev: sudo udevadm control --reload-rules && sudo udevadm trigger
#   4. Re-plug USB cables → symlinks appear immediately
#
# Verify: ls -la /dev/reach_*

set -euo pipefail

RULES_FILE="/etc/udev/rules.d/99-reach-rs.rules"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="auto"
MANUAL_DEVICE=""
LEFT_DEVICE=""
RIGHT_DEVICE=""
AUTO_YES=0
DRY_RUN=0

usage() {
    cat <<'EOF'
Usage:
  sudo bash scripts/setup_udev_reach_rs.sh [options]

Options:
  --single                 Force single-rover mode
  --dual                   Force dual-rover mode
  --device /dev/ttyACM0    Use this serial device as the single rover
  --left-device  /dev/ttyACM0
  --right-device /dev/ttyACM1
  -y, --yes                Non-interactive confirmation
  --dry-run                Show detected devices / rules without writing udev rules
  -h, --help               Show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --single) MODE="single" ;;
        --dual) MODE="dual" ;;
        --device)
            shift
            MANUAL_DEVICE="${1:-}"
            ;;
        --device=*)
            MANUAL_DEVICE="${1#*=}"
            ;;
        --left-device)
            shift
            LEFT_DEVICE="${1:-}"
            ;;
        --left-device=*)
            LEFT_DEVICE="${1#*=}"
            ;;
        --right-device)
            shift
            RIGHT_DEVICE="${1:-}"
            ;;
        --right-device=*)
            RIGHT_DEVICE="${1#*=}"
            ;;
        -y|--yes) AUTO_YES=1 ;;
        --dry-run) DRY_RUN=1 ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "❌  Unknown option: $1"
            usage
            exit 1
            ;;
    esac
    shift
done

print_header() {
    echo ""
    echo "══════════════════════════════════════════"
    echo "   Emlid Reach RS — udev setup"
    echo "══════════════════════════════════════════"
    echo ""
}

detect_reach_devices() {
    local devices=()
    for tty in /dev/ttyACM* /dev/ttyUSB*; do
        [ -e "$tty" ] || continue
        local product
        product=$(udevadm info -a -p "$(udevadm info -q path -n "$tty")" 2>/dev/null \
                  | grep -m1 'ATTRS{product}' | awk -F'"' '{print $2}')
        if echo "$product" | grep -qi "reach\|emlid\|gnss\|ublox"; then
            devices+=("$tty")
        fi
    done
    printf '%s\n' "${devices[@]}"
}

list_serial_candidates() {
    local found=0
    for tty in /dev/ttyACM* /dev/ttyUSB*; do
        [ -e "$tty" ] || continue
        found=1
        local info product vendor product_id serial
        info=$(udevadm info -a -p "$(udevadm info -q path -n "$tty")" 2>/dev/null || true)
        product=$(echo "$info" | grep -m1 'ATTRS{product}' | awk -F'"' '{print $2}')
        vendor=$(echo "$info" | grep -m1 'ATTRS{idVendor}' | awk -F'"' '{print $2}')
        product_id=$(echo "$info" | grep -m1 'ATTRS{idProduct}' | awk -F'"' '{print $2}')
        serial=$(echo "$info" | grep -m1 'ATTRS{serial}' | awk -F'"' '{print $2}')
        echo "    - $tty  vendor=${vendor:-?} pid=${product_id:-?} serial=${serial:-?} product='${product:-?}'"
    done
    if [ "$found" -eq 0 ]; then
        echo "    (no /dev/ttyACM* or /dev/ttyUSB* devices found)"
    fi
}

get_device_info() {
    local tty="$1"
    local path
    path=$(udevadm info -q path -n "$tty" 2>/dev/null)
    if [ -z "$path" ]; then
        echo "ERROR: Cannot get path for $tty" >&2
        return 1
    fi
    local info
    info=$(udevadm info -a -p "$path" 2>/dev/null)

    local serial vendor product_id product_name
    serial=$(echo "$info" | grep -m1 'ATTRS{serial}' | awk -F'"' '{print $2}')
    vendor=$(echo "$info" | grep -m1 'ATTRS{idVendor}' | awk -F'"' '{print $2}')
    product_id=$(echo "$info" | grep -m1 'ATTRS{idProduct}' | awk -F'"' '{print $2}')
    product_name=$(echo "$info" | grep -m1 'ATTRS{product}' | awk -F'"' '{print $2}')

    echo "device=$tty serial=$serial vendor=$vendor product_id=$product_id product=$product_name"
}

print_single_rover_rules() {
    local vendor="$1" pid="$2" serial="$3"
    cat << RULES
# Emlid Reach RS — single-antenna rover
# Generated by setup_udev_reach_rs.sh on $(date -Iseconds)
# One receiver → /dev/reach_rover  (single-antenna RTK, rear-center mount)

SUBSYSTEM=="tty", ATTRS{idVendor}=="${vendor}", ATTRS{idProduct}=="${pid}", ATTRS{serial}=="${serial}", SYMLINK+="reach_rover", MODE="0666", GROUP="dialout"
RULES
}

write_single_rover_rules() {
    local vendor="$1" pid="$2" serial="$3"
    print_single_rover_rules "$vendor" "$pid" "$serial" > "$RULES_FILE"
}

print_dual_rover_rules() {
    local lv="$1" lp="$2" ls="$3"   # left vendor/pid/serial
    local rv="$4" rp="$5" rs="$6"   # right vendor/pid/serial
    cat << RULES
# Emlid Reach RS — dual-antenna setup
# Generated by setup_udev_reach_rs.sh on $(date -Iseconds)
# Left  → /dev/reach_left  (port side)
# Right → /dev/reach_right (starboard side)
# /dev/reach_rover aliases /dev/reach_left (primary rover)

# Left antenna (PORT side) → /dev/reach_left  + /dev/reach_rover
SUBSYSTEM=="tty", ATTRS{idVendor}=="${lv}", ATTRS{idProduct}=="${lp}", ATTRS{serial}=="${ls}", SYMLINK+="reach_left reach_rover", MODE="0666", GROUP="dialout"

# Right antenna (STARBOARD side) → /dev/reach_right
SUBSYSTEM=="tty", ATTRS{idVendor}=="${rv}", ATTRS{idProduct}=="${rp}", ATTRS{serial}=="${rs}", SYMLINK+="reach_right", MODE="0666", GROUP="dialout"
RULES
}

write_dual_rover_rules() {
    local lv="$1" lp="$2" ls="$3"   # left vendor/pid/serial
    local rv="$4" rp="$5" rs="$6"   # right vendor/pid/serial
    print_dual_rover_rules "$lv" "$lp" "$ls" "$rv" "$rp" "$rs" > "$RULES_FILE"
}

# ── Main ──────────────────────────────────────────────────────────────────────

print_header

if [ "$EUID" -ne 0 ] && [ "$DRY_RUN" -eq 0 ]; then
    echo "❌  This script should be run with sudo to install udev rules."
    echo "    Retry with:"
    echo "      sudo bash scripts/setup_udev_reach_rs.sh${MODE:+ ${MODE/auto/}}"
    echo ""
    echo "    If you just want to inspect devices first:"
    echo "      bash scripts/setup_udev_reach_rs.sh --dry-run"
    exit 1
fi

echo "[1/4] Detecting connected Reach RS receivers..."
mapfile -t DEVICES < <(detect_reach_devices)

if [ -n "$MANUAL_DEVICE" ]; then
    if [ ! -e "$MANUAL_DEVICE" ]; then
        echo "❌  Manual device not found: $MANUAL_DEVICE"
        exit 1
    fi
    DEVICES=("$MANUAL_DEVICE")
    MODE="${MODE/auto/single}"
fi

if [ -n "$LEFT_DEVICE" ] || [ -n "$RIGHT_DEVICE" ]; then
    if [ ! -e "${LEFT_DEVICE:-}" ] || [ ! -e "${RIGHT_DEVICE:-}" ]; then
        echo "❌  --left-device and --right-device must both exist."
        exit 1
    fi
    DEVICES=("$LEFT_DEVICE" "$RIGHT_DEVICE")
    MODE="dual"
fi

if [ ${#DEVICES[@]} -eq 0 ] && [ "$MODE" = "single" ]; then
    mapfile -t CANDIDATES < <(for tty in /dev/ttyACM* /dev/ttyUSB*; do [ -e "$tty" ] && echo "$tty"; done)
    if [ ${#CANDIDATES[@]} -eq 1 ]; then
        DEVICES=("${CANDIDATES[0]}")
        echo "  No Reach-branded product string found."
        echo "  Falling back to the only serial candidate in single mode: ${DEVICES[0]}"
    fi
fi

if [ ${#DEVICES[@]} -eq 0 ]; then
    echo "❌  No Reach RS devices detected. Make sure:"
    echo "    - Receiver(s) are connected via USB"
    echo "    - This script runs with sudo"
    echo "    - The Reach RS is powered on"
    echo ""
    echo "    Visible serial candidates:"
    list_serial_candidates
    echo ""
    echo "    If you know the device, force single-rover setup with:"
    echo "      sudo bash scripts/setup_udev_reach_rs.sh --single --device /dev/ttyACM0"
    exit 1
fi

echo "  Found ${#DEVICES[@]} device(s):"
declare -A DEVICE_INFO_MAP
for dev in "${DEVICES[@]}"; do
    info=$(get_device_info "$dev")
    DEVICE_INFO_MAP["$dev"]="$info"
    local_serial=$(echo "$info" | grep -o 'serial=[^ ]*' | cut -d= -f2)
    local_product=$(echo "$info" | grep -o 'product=[^=]*$' | cut -d= -f2)
    echo "  → $dev  serial='$local_serial'  ($local_product)"
done

echo ""

# ── Single-antenna mode ───────────────────────────────────────────────────────
if [ "$MODE" = "single" ] || { [ "$MODE" = "auto" ] && [ ${#DEVICES[@]} -eq 1 ]; }; then
    echo "[2/4] Single receiver detected — configuring as /dev/reach_rover"
    DEV="${DEVICES[0]}"
    INFO="${DEVICE_INFO_MAP[$DEV]}"
    SERIAL=$(echo "$INFO" | grep -o 'serial=[^ ]*' | cut -d= -f2)
    VENDOR=$(echo "$INFO" | grep -o 'vendor=[^ ]*' | cut -d= -f2)
    PID=$(echo "$INFO" | grep -o 'product_id=[^ ]*' | cut -d= -f2)

    if [ -z "$SERIAL" ] || [ -z "$VENDOR" ] || [ -z "$PID" ]; then
        echo "❌  Incomplete udev info for $DEV."
        echo "    serial='${SERIAL:-}' vendor='${VENDOR:-}' pid='${PID:-}'"
        echo "    Run this for manual inspection:"
        echo "      udevadm info -a -p \$(udevadm info -q path -n $DEV)"
        exit 1
    fi

    echo ""
    echo "  Device: $DEV"
    echo "  Serial: $SERIAL"
    echo "  → Will create symlink: /dev/reach_rover"
    echo ""
    if [ "$AUTO_YES" -eq 0 ] && [ "$DRY_RUN" -eq 0 ]; then
        read -rp "  Proceed? [Y/n]: " confirm
        confirm="${confirm:-Y}"
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 0
        fi
    fi

    echo ""
    echo "[3/4] Generating udev rules → $RULES_FILE"
    if [ "$DRY_RUN" -eq 0 ]; then
        write_single_rover_rules "$VENDOR" "$PID" "$SERIAL"
        echo "  Wrote:"
        cat "$RULES_FILE"
    else
        echo "  Dry-run rules preview:"
        print_single_rover_rules "$VENDOR" "$PID" "$SERIAL"
    fi

# ── Dual-antenna mode ─────────────────────────────────────────────────────────
elif [ "$MODE" = "dual" ] || { [ "$MODE" = "auto" ] && [ ${#DEVICES[@]} -ge 2 ]; }; then
    DEV_A="${DEVICES[0]}"
    DEV_B="${DEVICES[1]}"
    INFO_A="${DEVICE_INFO_MAP[$DEV_A]}"
    INFO_B="${DEVICE_INFO_MAP[$DEV_B]}"
    SERIAL_A=$(echo "$INFO_A" | grep -o 'serial=[^ ]*' | cut -d= -f2)
    SERIAL_B=$(echo "$INFO_B" | grep -o 'serial=[^ ]*' | cut -d= -f2)
    VENDOR_A=$(echo "$INFO_A" | grep -o 'vendor=[^ ]*' | cut -d= -f2)
    VENDOR_B=$(echo "$INFO_B" | grep -o 'vendor=[^ ]*' | cut -d= -f2)
    PID_A=$(echo "$INFO_A" | grep -o 'product_id=[^ ]*' | cut -d= -f2)
    PID_B=$(echo "$INFO_B" | grep -o 'product_id=[^ ]*' | cut -d= -f2)

    echo "[2/4] Two receivers detected — assign left/right roles"
    echo "  The LEFT (port side) antenna also becomes /dev/reach_rover (primary)."
    echo ""
    echo "  Device A: $DEV_A  serial: $SERIAL_A"
    echo "  Device B: $DEV_B  serial: $SERIAL_B"
    echo ""
    echo "  Which device is the LEFT (port) antenna?"
    echo "    [A] $DEV_A — serial: $SERIAL_A"
    echo "    [B] $DEV_B — serial: $SERIAL_B"
    echo ""
    if [ "$AUTO_YES" -eq 1 ]; then
        choice="A"
    else
        read -rp "  Enter A or B: " choice
        choice="${choice^^}"
    fi

    if [ "$choice" = "A" ]; then
        L_V="$VENDOR_A"; L_P="$PID_A"; L_S="$SERIAL_A"
        R_V="$VENDOR_B"; R_P="$PID_B"; R_S="$SERIAL_B"
    elif [ "$choice" = "B" ]; then
        L_V="$VENDOR_B"; L_P="$PID_B"; L_S="$SERIAL_B"
        R_V="$VENDOR_A"; R_P="$PID_A"; R_S="$SERIAL_A"
    else
        echo "❌  Invalid choice. Aborting."
        exit 1
    fi

    echo ""
    echo "  ✓  LEFT  → /dev/reach_left + /dev/reach_rover  (serial: $L_S)"
    echo "  ✓  RIGHT → /dev/reach_right                    (serial: $R_S)"

    echo ""
    echo "[3/4] Generating udev rules → $RULES_FILE"
    if [ "$DRY_RUN" -eq 0 ]; then
        write_dual_rover_rules "$L_V" "$L_P" "$L_S" "$R_V" "$R_P" "$R_S"
        echo "  Wrote:"
        cat "$RULES_FILE"
    else
        echo "  Dry-run rules preview:"
        print_dual_rover_rules "$L_V" "$L_P" "$L_S" "$R_V" "$R_P" "$R_S"
    fi
fi

echo ""
echo "[4/4] Reloading udev rules..."
if [ "$DRY_RUN" -eq 0 ]; then
    udevadm control --reload-rules
    udevadm trigger
else
    echo "  Dry-run: not writing rules, not reloading udev."
fi

echo ""
echo "══════════════════════════════════════════"
echo "  ✅  Done! Unplug and re-plug the USB cable(s)."
echo "  Verify: ls -la /dev/reach_*"
echo "══════════════════════════════════════════"
echo ""
