#!/usr/bin/env python3
"""Summarize motion-model horizon evaluations generated by evaluate_motion_model_horizon.py."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any

import yaml


def model_label(path: Path, suite_dir: Path) -> str:
    rel = path.relative_to(suite_dir)
    parts = rel.parts[:-1]
    return "/".join(parts) if parts else path.stem.replace("_prediction_summary", "")


def load_summaries(suite_dir: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for summary_path in sorted(suite_dir.rglob("*_prediction_summary.yaml")):
        summary = yaml.safe_load(summary_path.read_text(encoding="utf-8")) or {}
        settings = summary.get("settings", {})
        for horizon, values in (summary.get("by_horizon_s") or {}).items():
            position = values.get("position_m") or {}
            yaw = values.get("yaw_rad") or {}
            rows.append(
                {
                    "model": model_label(summary_path, suite_dir),
                    "summary_path": str(summary_path),
                    "model_kind": settings.get("model_kind"),
                    "speed_source": settings.get("speed_source"),
                    "articulation_source": settings.get("articulation_source"),
                    "curvature_model": settings.get("curvature_model"),
                    "tau_v_s": settings.get("tau_v_s"),
                    "tau_r_s": settings.get("tau_r_s"),
                    "tau_phi_s": settings.get("tau_phi_s"),
                    "horizon_s": float(horizon),
                    "samples": values.get("samples"),
                    "position_rmse_m": position.get("rmse"),
                    "position_p95_m": position.get("p95_abs"),
                    "position_max_m": position.get("max_abs"),
                    "yaw_rmse_rad": yaw.get("rmse"),
                    "yaw_p95_rad": yaw.get("p95_abs"),
                    "yaw_max_rad": yaw.get("max_abs"),
                }
            )
    rows.sort(key=lambda row: (str(row["model"]), float(row["horizon_s"])))
    return rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_plots(suite_dir: Path, rows: list[dict[str, Any]]) -> dict[str, str]:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return {}

    outputs: dict[str, str] = {}
    models = sorted({str(row["model"]) for row in rows})

    def plot_metric(metric: str, ylabel: str, filename: str) -> None:
        plt.figure(figsize=(11, 6))
        for model in models:
            model_rows = sorted(
                [row for row in rows if row["model"] == model],
                key=lambda row: float(row["horizon_s"]),
            )
            horizons = [float(row["horizon_s"]) for row in model_rows]
            values = [float(row[metric]) for row in model_rows if row[metric] is not None]
            if len(values) != len(horizons):
                continue
            plt.plot(horizons, values, marker="o", label=model)
        plt.xlabel("prediction horizon [s]")
        plt.ylabel(ylabel)
        plt.title(ylabel + " by motion model")
        plt.grid(True, alpha=0.4)
        plt.legend(fontsize=8)
        plt.tight_layout()
        path = suite_dir / filename
        plt.savefig(path, dpi=150)
        plt.close()
        outputs[metric] = str(path)

    plot_metric("position_rmse_m", "position RMSE [m]", "comparison_position_rmse.png")
    plot_metric("position_p95_m", "position P95 [m]", "comparison_position_p95.png")
    plot_metric("yaw_rmse_rad", "yaw RMSE [rad]", "comparison_yaw_rmse.png")
    return outputs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("suite_dir", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    suite_dir = args.suite_dir.expanduser()
    rows = load_summaries(suite_dir)
    out_csv = suite_dir / "comparison_summary.csv"
    write_csv(out_csv, rows)
    outputs = write_plots(suite_dir, rows)
    result = {
        "suite_dir": str(suite_dir),
        "models": sorted({row["model"] for row in rows}),
        "rows": len(rows),
        "csv": str(out_csv),
        "plots": outputs,
    }
    print(yaml.safe_dump(result, sort_keys=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
